# Generated by Django 4.2.7 on 2023-11-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_genre_delete_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Products',
        ),
    ]
